# Generated by Django 4.0.6 on 2022-07-10 10:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Timezone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("expiry_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("remind_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(null=True)),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "timezone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="App.timezone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain_name", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "domain_unique_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("request_body", models.TextField()),
                ("reminders", models.ManyToManyField(to="App.reminder")),
            ],
        ),
    ]
