# Generated by Django 4.0.6 on 2022-11-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="welcome_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
