# Generated by Django 4.0.6 on 2022-11-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_domain_welcome_email_sent"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain_name", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
